subject: Velkommen til BetterSalesman!
body: |
  <p>Hej *|display_name|*!</p>

  <p>Velkommen til BetterSalesman!</p>

  <p>*|message|*</p>

  <p>
  <a href="https://itunes.apple.com/us/app/bettersalesman/id911319758">https://itunes.apple.com/us/app/bettersalesman/id911319758</a>
  </p>

  <p>Dette er din adgangskode, som du kan Ã¦ndre senere:</p>

  <p>Username = *|email|*</p>

  <p>Password = *|password|*</p>
